_resources:
    imports:
        - config/services.yml
        - config/db.yml

parameters:
    db.connection_str: "sqlite://memory"
    cache_dir: "/tmp"
    user: "!env USER"
    version: $env("GIT_COMMIT_HASH")-beta

services:
    test.service.DBService:
        arguments:
            connection_str: "${db.connection_str}"
            cache_dir: "${cache_dir}/${USER}/db"

    test.service.DatabaseService:
        factory: test.service.DbService.get_connection_from_pool