site_name: WireUp
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Parameters: parameters.md
  - Advanced Topics:
      - Factory functions: factory_functions.md
      - Working with Interfaces: interfaces.md
      - Manual configuration: manual_configuration.md
      - Multiple containers: multiple_containers.md
  - Misc:
    - Introduce to an existing project: introduce_to_an_existing_project.md
  - Examples:
      - FastAPI: examples/fastapi.md
theme: readthedocs
markdown_extensions:
  - admonition
docs_dir: pages
