site_name: WireUp
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Advanced Topics:
      - Working with Interfaces: interfaces.md
      - Manual configuration: manual_configuration.md
      - Multiple containers: multiple_containers.md
  - Examples:
      - Fastapi: examples/fastapi.md
theme: readthedocs
docs_dir: pages