name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create venv
        run: python -m venv .venv
      - name: Install dependencies
        run: |
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/pip install poetry
          .venv/bin/poetry install --no-root
      - name: Lint
        run: |
          .venv/bin/poetry run ruff --format=github wireup
      - name: Check typing
        run: |
          .venv/bin/poetry run mypy wireup --strict
      - name: Check formatting
        run: |
          .venv/bin/poetry run black --check .
      - name: Run tests
        run: |
          .venv/bin/python -m unittest discover -s test/
